name: Auto Cherry-Pick from Upstream

on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: "Base branch to create the PR against"
        required: true
        default: "main"

permissions:
  contents: write
  pull-requests: write
  packages: read
  issues: write

jobs:
  cherry-pick:
    uses: step-security/reusable-workflows/.github/workflows/auto_cherry_pick.yaml@v1
    with:
      original-owner: "martialonline"
      repo-name: "workflow-status"
      base_branch: ${{ inputs.base_branch }}
