name: Tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'license'
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'license'
      - '**.md'
    types:
      - opened
      - reopened
      - synchronize

jobs:

  test:
    name: Test-Action
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Test Action
        id: test
        uses: ./
      - name: Get Test Output
        run: echo "Workflow Status '${{ steps.test.outputs.status }}'"