name: Tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'license'
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'license'
      - '**.md'
    types:
      - opened
      - reopened
      - synchronize

jobs:

  test:
    name: Test-Action
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Checkout Repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Test Action
        id: test
        uses: ./
      - name: Get Test Output
        run: echo "Workflow Status '${{ steps.test.outputs.status }}'"